"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
    return (
        <div className="min-h-screen bg-black text-white">
            {/* Header */}
            <div className="border-b border-white/10 bg-black/50 backdrop-blur-sm sticky top-0 z-10">
                <div className="max-w-4xl mx-auto px-6 py-4">
                    <Link
                        href="/login"
                        className="inline-flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Back
                    </Link>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-4xl mx-auto px-6 py-12">
                <h1 className="text-4xl font-display font-bold mb-2 bg-gradient-to-r from-white via-purple-200 to-white bg-clip-text text-transparent">
                    Privacy Policy
                </h1>
                <p className="text-gray-400 mb-8">Last updated: 5 February 2026</p>

                <div className="prose prose-invert prose-purple max-w-none space-y-8">
                    {/* Introduction */}
                    <section>
                        <p className="text-gray-300 leading-relaxed">
                            This Privacy Policy describes how Xolvit Pty Ltd ACN 676 743 815 (&quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot;) collects, uses, and discloses Your Personal Data when You use the PresX service (&quot;the Service&quot;) and tells You about Your privacy rights.
                        </p>
                        <p className="text-gray-300 leading-relaxed mt-4">
                            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                        </p>
                    </section>

                    {/* 1. Interpretation and Definitions */}
                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">1. Interpretation and Definitions</h2>

                        <h3 className="text-xl font-semibold text-purple-400 mb-3">1.1 Interpretation</h3>
                        <p className="text-gray-300 leading-relaxed">
                            The words of which the initial letter is capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </p>

                        <h3 className="text-xl font-semibold text-purple-400 mb-3 mt-6">1.2 Definitions</h3>
                        <p className="text-gray-300 leading-relaxed mb-3">For the purposes of this Privacy Policy:</p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                            <li><strong className="text-white">AI Analysis Data</strong> means data generated by the Service&apos;s automated analysis features, including feedback, scores, reports, evaluations, and other outputs produced when You submit Audio Data or other content for analysis.</li>
                            <li><strong className="text-white">Audio Data</strong> means audio recordings You submit to the Service for analysis, whether recorded directly through the Service or uploaded from another source.</li>
                            <li><strong className="text-white">Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Xolvit Pty Ltd ACN 676 743 815, Level 35, 1 Farrer Place, Sydney NSW 2000.</li>
                            <li><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><strong className="text-white">Country</strong> refers to Australia.</li>
                            <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                            <li><strong className="text-white">Service</strong> refers to the PresX service.</li>
                            <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                            <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>
                    </section>

                    {/* 2. Collecting and Using Your Personal Data */}
                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">2. Collecting and Using Your Personal Data</h2>

                        <h3 className="text-xl font-semibold text-purple-400 mb-3">2.1 Types of Data Collected</h3>

                        <h4 className="text-lg font-semibold text-white mb-2 mt-4">Personal Data</h4>
                        <p className="text-gray-300 leading-relaxed mb-3">
                            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Usage Data</li>
                        </ul>

                        <h4 className="text-lg font-semibold text-white mb-2 mt-6">Usage Data</h4>
                        <p className="text-gray-300 leading-relaxed">
                            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        </p>

                        <h4 className="text-lg font-semibold text-white mb-2 mt-6">Audio Data and AI Analysis Data</h4>
                        <p className="text-gray-300 leading-relaxed mb-3">
                            The Service allows You to submit Audio Data (audio recordings) for automated analysis. When You do so:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li>The Audio Data is processed by the Service to generate AI Analysis Data (such as feedback, scores, and reports).</li>
                            <li>Audio Data may be temporarily stored to support playback and operational features, and is then removed from active systems in accordance with automated lifecycle policies.</li>
                            <li>The AI Analysis Data is retained until You delete it or Your Account is deleted.</li>
                            <li>Where You participate in challenges on the Service, AI Analysis Data may be shared with the organisation hosting the relevant challenge.</li>
                        </ul>

                        <h4 className="text-lg font-semibold text-white mb-2 mt-6">Information from Third-Party Social Media Services</h4>
                        <p className="text-gray-300 leading-relaxed mb-3">
                            The Company allows You to create an account and log in to use the Service through third-party Social Media Services such as Google. If You decide to register through or otherwise grant us access to a third-party Social Media Service, We may collect Personal Data that is already associated with Your Social Media Service&apos;s account, such as Your name and Your email address.
                        </p>

                        <h4 className="text-lg font-semibold text-white mb-2 mt-6">Tracking Technologies and Cookies</h4>
                        <p className="text-gray-300 leading-relaxed mb-3">
                            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for the purposes set out below:
                        </p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li><strong className="text-white">Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
                            <li><strong className="text-white">Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
                        </ul>
                    </section>

                    {/* 3. Use of Your Personal Data */}
                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">3. Use of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed mb-3">The Company may use Personal Data for the following purposes:</p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li><strong className="text-white">To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                            <li><strong className="text-white">To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                            <li><strong className="text-white">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                            <li><strong className="text-white">To contact You:</strong> To contact You by email or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
                            <li><strong className="text-white">To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
                            <li><strong className="text-white">To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                            <li><strong className="text-white">For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                            <li><strong className="text-white">For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                        </ul>
                    </section>

                    {/* 4. Sharing of Your Personal Data */}
                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">4. Sharing of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed mb-3">We may share Your Personal Data in the following situations:</p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li><strong className="text-white">With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyse the use of our Service, to contact You.</li>
                            <li><strong className="text-white">With Challenge Hosts:</strong> Where You participate in challenges on the Service, AI Analysis Data and brand engagement survey responses may be shared with the organisation hosting the relevant challenge.</li>
                            <li><strong className="text-white">For business transfers:</strong> We may share or transfer Your Personal Data in connection with any merger, sale of Company assets, financing, or acquisition.</li>
                            <li><strong className="text-white">With Affiliates:</strong> We may share Your Personal Data with Our Affiliates, in which case we will require those Affiliates to honour this Privacy Policy.</li>
                            <li><strong className="text-white">With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
                            <li><strong className="text-white">With other users:</strong> Where You participate in challenges, Your submitted content, name, profile information may be visible to other registered users.</li>
                            <li><strong className="text-white">With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
                            <li><strong className="text-white">For legal requirements:</strong> We may disclose Your Personal Data where required to do so by law.</li>
                        </ul>
                    </section>

                    {/* 5-12. Remaining Sections */}
                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">5. Retention of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed">
                            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                        </p>
                        <p className="text-gray-300 leading-relaxed mt-4">
                            Audio Data submitted for analysis is processed and stored only as necessary to generate the AI Analysis Data and support playback features, then removed from active systems. Audio Data may be retained in temporary storage (for example, for up to three months) and then deleted automatically.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">6. Transfer of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed">
                            Your Personal Data is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">7. Disclosure of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed mb-3">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                        <ul className="list-disc list-inside space-y-2 text-gray-300 ml-4">
                            <li>Comply with a legal obligation</li>
                            <li>Protect and defend the rights or property of the Company</li>
                            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                            <li>Protect the personal safety of users of the Service or the public</li>
                            <li>Protect against legal liability</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">8. Security of Your Personal Data</h2>
                        <p className="text-gray-300 leading-relaxed">
                            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">9. Children&apos;s Privacy</h2>
                        <p className="text-gray-300 leading-relaxed">
                            The Service is not intended for use by children under the age of 13 without the involvement or consent of a parent, guardian, or educational institution. The Company does not knowingly collect Personal Data directly from children under 13 except where access is provided through an educational institution or with appropriate consent.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">10. Links to Other Websites</h2>
                        <p className="text-gray-300 leading-relaxed">
                            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the privacy policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">11. Changes to this Privacy Policy</h2>
                        <p className="text-gray-300 leading-relaxed">
                            We may update this Privacy Policy from time to time. When We do, We will update the &quot;Last updated&quot; date at the top of this Privacy Policy and publish the revised version on this page. You are encouraged to review this Privacy Policy periodically to stay informed about how We protect Your Personal Data.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-display font-bold text-white mb-4">12. Contact Us</h2>
                        <p className="text-gray-300 leading-relaxed">
                            If you have any questions about this Privacy Policy, You can contact us at{" "}
                            <a href="mailto:info@xolvit.io" className="text-purple-400 hover:text-purple-300 transition-colors">
                                info@xolvit.io
                            </a>
                        </p>
                    </section>
                </div>

                {/* Back to top */}
                <div className="mt-12 pt-8 border-t border-white/10">
                    <Link
                        href="/login"
                        className="inline-flex items-center gap-2 text-purple-400 hover:text-purple-300 transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Back to Login
                    </Link>
                </div>
            </div>
        </div>
    );
}
